---
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu@18
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - name: Install SQLx CLI
        run: cargo install sqlx-cli || true
      - name: Create Database Directory
        run: mkdir -p ${{ github.workspace }}/data
      - env:
          DATABASE_URL: sqlite://${{ github.workspace }}/data/newsletter.sqlite
        name: Create Database
        run: |
          echo "DATABASE_URL=${DATABASE_URL}" >> $GITHUB_ENV
          cargo sqlx database create

      - name: Run Migrations
        run: cargo sqlx migrate run
      - name: Build
        run: cargo check
      - name: Build
        run: cargo build
name: Rust Code Validation
'on':
  push:
    branches:
      - main